/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;

/**
 *
 * @author Pronatec Tarde
 */
public class telaMenu extends javax.swing.JFrame {

    /**
     * Creates new form telaMenu
     */
    public telaMenu() {
        initComponents();
        setIcon();
    }
    
    public void setIcon()
   {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/SS2.png")));
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JDesktopPane();
        lblLogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnRegistro = new javax.swing.JMenu();
        mnClientes = new javax.swing.JMenuItem();
        mnProdutos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnListagens = new javax.swing.JMenu();
        mnRelatorios = new javax.swing.JMenu();
        mnPedidosdia = new javax.swing.JMenuItem();
        mnPedidossemana = new javax.swing.JMenuItem();
        mnPedidosperiodo = new javax.swing.JMenuItem();
        mnConsultas = new javax.swing.JMenu();
        mnPedidoscliente = new javax.swing.JMenuItem();
        mnFaturamentototal = new javax.swing.JMenuItem();
        mnUsuario = new javax.swing.JMenu();
        mnNovoUsuario = new javax.swing.JMenuItem();
        mnNovoUsuarioSDI = new javax.swing.JMenuItem();
        mnSobre = new javax.swing.JMenu();
        mnVersao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        lblLogin.setBackground(new java.awt.Color(255, 255, 255));
        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogin.setText("Usuário");

        pnPrincipal.setLayer(lblLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogin)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPrincipalLayout.createSequentialGroup()
                .addComponent(lblLogin)
                .addGap(0, 371, Short.MAX_VALUE))
        );

        mnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder.png"))); // NOI18N
        mnRegistro.setText("Registro");

        mnClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        mnClientes.setText("Clientes");
        mnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnClientesActionPerformed(evt);
            }
        });
        mnRegistro.add(mnClientes);

        mnProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        mnProdutos.setText("Produtos");
        mnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnProdutosActionPerformed(evt);
            }
        });
        mnRegistro.add(mnProdutos);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.png"))); // NOI18N
        jMenuItem1.setText("Pedido");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnRegistro.add(jMenuItem1);

        jMenuBar1.add(mnRegistro);

        mnListagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder_table.png"))); // NOI18N
        mnListagens.setText("Listagens");

        mnRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.png"))); // NOI18N
        mnRelatorios.setText("Relatório de Pedidos");

        mnPedidosdia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mnPedidosdia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        mnPedidosdia.setText("Pedidos do Dia");
        mnRelatorios.add(mnPedidosdia);

        mnPedidossemana.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mnPedidossemana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        mnPedidossemana.setText("Pedidos da Semana");
        mnRelatorios.add(mnPedidossemana);

        mnPedidosperiodo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mnPedidosperiodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        mnPedidosperiodo.setText("Pedidos por Período");
        mnRelatorios.add(mnPedidosperiodo);

        mnListagens.add(mnRelatorios);

        mnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database.png"))); // NOI18N
        mnConsultas.setText("Consultas");

        mnPedidoscliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnPedidoscliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_table.png"))); // NOI18N
        mnPedidoscliente.setText("Pedidos por Cliente");
        mnConsultas.add(mnPedidoscliente);

        mnFaturamentototal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mnFaturamentototal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/database_table.png"))); // NOI18N
        mnFaturamentototal.setText("Faturamento Total");
        mnConsultas.add(mnFaturamentototal);

        mnListagens.add(mnConsultas);

        jMenuBar1.add(mnListagens);

        mnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_suit.png"))); // NOI18N
        mnUsuario.setText("Usuário");

        mnNovoUsuario.setText("Novo Usuário");
        mnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNovoUsuarioActionPerformed(evt);
            }
        });
        mnUsuario.add(mnNovoUsuario);

        mnNovoUsuarioSDI.setText("Novo Usuário SDI");
        mnNovoUsuarioSDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNovoUsuarioSDIActionPerformed(evt);
            }
        });
        mnUsuario.add(mnNovoUsuarioSDI);

        jMenuBar1.add(mnUsuario);

        mnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/world.png"))); // NOI18N
        mnSobre.setText("Sobre");

        mnVersao.setText("Versão");
        mnVersao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVersaoActionPerformed(evt);
            }
        });
        mnSobre.add(mnVersao);

        jMenuBar1.add(mnSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPrincipal)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNovoUsuarioActionPerformed
        telaNovoUsuario telaUser = new telaNovoUsuario();
        pnPrincipal.add(telaUser);
        telaUser.setVisible(true);
        
        
    }//GEN-LAST:event_mnNovoUsuarioActionPerformed

    private void mnNovoUsuarioSDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNovoUsuarioSDIActionPerformed
        new telaNovoUsuarioSDI().setVisible(true);
        
        
        
    }//GEN-LAST:event_mnNovoUsuarioSDIActionPerformed

    private void mnVersaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVersaoActionPerformed
        telaSobreMDI telaSobre = new telaSobreMDI();
        pnPrincipal.add(telaSobre);
        telaSobre.setVisible(true);


    }//GEN-LAST:event_mnVersaoActionPerformed

    private void mnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnProdutosActionPerformed
        telaControleProdutos telaProd = new telaControleProdutos();
        pnPrincipal.add(telaProd);
        telaProd.setVisible(true);
    }//GEN-LAST:event_mnProdutosActionPerformed

    private void mnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnClientesActionPerformed
        telaControleCliente telaCliente = new telaControleCliente();
        pnPrincipal.add(telaCliente);
        telaCliente.setVisible(true);
    }//GEN-LAST:event_mnClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        telaControlePedido telaPedido = new telaControlePedido();
        pnPrincipal.add(telaPedido);
        telaPedido.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JLabel lblLogin;
    private javax.swing.JMenuItem mnClientes;
    private javax.swing.JMenu mnConsultas;
    private javax.swing.JMenuItem mnFaturamentototal;
    private javax.swing.JMenu mnListagens;
    private javax.swing.JMenuItem mnNovoUsuario;
    private javax.swing.JMenuItem mnNovoUsuarioSDI;
    private javax.swing.JMenuItem mnPedidoscliente;
    private javax.swing.JMenuItem mnPedidosdia;
    private javax.swing.JMenuItem mnPedidosperiodo;
    private javax.swing.JMenuItem mnPedidossemana;
    private javax.swing.JMenuItem mnProdutos;
    private javax.swing.JMenu mnRegistro;
    private javax.swing.JMenu mnRelatorios;
    private javax.swing.JMenu mnSobre;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JMenuItem mnVersao;
    private javax.swing.JDesktopPane pnPrincipal;
    // End of variables declaration//GEN-END:variables
}
